modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ripiters/HBMs-Nuclear-Horizons/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/ripiters/HBMs-Nuclear-Horizons/main/version.json"
    displayURL="https://modrinth.com/project/hbms-nuclear-horizons"
    logoFile="icon.png"
    credits="Based on HBM's Nuclear Tech Mod by Hbm79, Extended version by Drillgon200 and CE by Alcater. Licensed under GPL v3.0."
    authors="ripiters"
    description='''
HBM's Nuclear Horizons - Modern port and expansion of the nuclear technology experience.
'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"